name: Copy all to github pages

on:
  push:
    branches:
      - master

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: copy to hg-pages
        run: |
          git config --global user.name 'Luka Popijac'
          git config --global user.email 'luka.popijac@gmail.com'
          git fetch
          git checkout gh-pages
          git checkout master .     # copy all files from master branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin gh-pages
